# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BagusMantonafi
email: bagus.manto1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  mbahgoez merupakan website yang berisi informasi seputar Pemograman utamanya pemograman Web dan Pemograman Mobile. berawal dari sang owner yang mempunyai ilmu yang banyak namun selalu mudah lupa untuk mengingat ilmu yang baru dipelajarinya.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mbahgoez.github.io" # the base hostname & protocol for your site
facebook_username: mbah.goezt
twitter_username: BagusMantonafi
github_username:  mbahgoez
permalink: /blog/:year/:month/:day/:title/


# Build settings
markdown: kramdown
sass:
 style: compressed
